version: '3'
services:
  api:
    build:
      context: docker/php
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html/
    ports:
      - '80:80'
    depends_on:
      - mariadb
    restart: always
  test:
    build:
      context: docker/php
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html/
    ports:
      - '8080:80'
    depends_on:
      - mariadb
    restart: always

  mariadb:
    image: mariadb:latest
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=user_management

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - "8081:80"
    environment:
      - PMA_ARBITRARY=1
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_HOST=mariadb

volumes:
  mariadb_data:
